"""Top-level README generation for the student template repository."""
import logging
import os

from sqlalchemy.orm import Session, joinedload

logger = logging.getLogger(__name__)


def generate_main_readme(db: Session, course, template_repo_path: str) -> list:
    """(Re)write the template's README with ALL deployed assignments.

    Includes 'deploying' rows because the README is generated BEFORE the
    final status update of the current run. Returns the deployed/deploying
    contents used, so the caller can gate the git push on them.
    """
    from ...model.course import CourseContent
    from ...model.deployment import CourseContentDeployment
    from ...model.example import ExampleVersion

    course_id = course.id

    all_deployed_contents = db.query(CourseContent).options(
            joinedload(CourseContent.deployment)
                .joinedload(CourseContentDeployment.example_version)
                .joinedload(ExampleVersion.example)
        ).filter(
        CourseContent.course_id == course_id,
        CourseContent.archived_at.is_(None),
        CourseContent.deployment.has(
            CourseContentDeployment.deployment_status.in_(['deployed', 'deploying'])
        )
    ).order_by(CourseContent.path).all()

    logger.info(f"Found {len(all_deployed_contents)} deployed/deploying assignments for README generation")

    main_readme_path = os.path.join(template_repo_path, "README.md")
    with open(main_readme_path, 'w') as f:
        f.write(f"# {course.title} - Student Template\n\n")
        f.write(f"This repository contains {len(all_deployed_contents)} assignments for {course.title}.\n\n")

        if all_deployed_contents:
            f.write(f"## Assignment Structure\n\n")
            f.write(f"| Content Path | Assignment Directory | Title | Version |\n")
            f.write(f"|-------------|---------------------|-------|----------|\n")

            # Fetch all course contents to build complete path hierarchy
            all_contents = db.query(CourseContent).filter(
                CourseContent.course_id == course_id,
                CourseContent.archived_at.is_(None)
            ).all()

            path_to_title = {str(c.path): c.title for c in all_contents}

            for content in all_deployed_contents:
                if content.deployment and content.deployment.example_version:
                    example = content.deployment.example_version.example
                    version = content.deployment.example_version.version_tag

                    # Build title path with "/" separation, resolving each
                    # ancestor path segment to its title where possible
                    path_parts = str(content.path).split('.')
                    title_parts = []
                    for i, part in enumerate(path_parts):
                        current_path = '.'.join(path_parts[:i + 1])
                        title_parts.append(path_to_title.get(current_path, part))

                    title_path = " / ".join(title_parts)
                    directory_link = f"[`{example.identifier}/`](./{example.identifier})"

                    f.write(f"| {title_path} | {directory_link} | {content.title} | {version} |\n")
        else:
            f.write(f"*No assignments deployed yet.*\n\n")

        f.write(f"\n## Instructions\n\n")
        f.write(f"Each assignment is in its own directory. Navigate to the assignment directory and follow the instructions in its README.md file.\n\n")
        f.write(f"## Submission\n\n")
        f.write(f"Follow your course submission guidelines for each assignment.\n\n")
        f.write(f"---\n")
        f.write(f"*Generated by Computor*\n")

    logger.info(f"Generated main README.md with {len(all_deployed_contents)} deployed assignments (current state)")
    return all_deployed_contents
