"""Add submit field to submission_artifact

Revision ID: 73d21fec62d8
Revises: f5a6b7c8d9e0
Create Date: 2025-09-30 01:53:06.529291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d21fec62d8'
down_revision: Union[str, None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_content', 'example_version_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Reference to specific ExampleVersion',
               existing_nullable=True)
    op.drop_constraint('course_content_example_version_id_fkey', 'course_content', type_='foreignkey')
    op.create_foreign_key(None, 'course_content', 'example_version', ['example_version_id'], ['id'], ondelete='SET NULL')
    op.alter_column('deployment_history', 'action',
               existing_type=sa.VARCHAR(length=32),
               comment='Action type: assigned, reassigned, deploying, deployed, failed, unassigned, updated',
               existing_comment='Action type: assigned, reassigned, deployed, failed, unassigned, updated',
               existing_nullable=False)
    op.alter_column('result', 'result',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('submission_artifact', sa.Column('submit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_artifact', 'submit')
    op.alter_column('result', 'result',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('deployment_history', 'action',
               existing_type=sa.VARCHAR(length=32),
               comment='Action type: assigned, reassigned, deployed, failed, unassigned, updated',
               existing_comment='Action type: assigned, reassigned, deploying, deployed, failed, unassigned, updated',
               existing_nullable=False)
    op.drop_constraint(None, 'course_content', type_='foreignkey')
    op.create_foreign_key('course_content_example_version_id_fkey', 'course_content', 'example_version', ['example_version_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.alter_column('course_content', 'example_version_id',
               existing_type=postgresql.UUID(),
               comment='Reference to specific ExampleVersion',
               existing_nullable=True)
    # ### end Alembic commands ###
