"""Add unique constraint and composite index on submission_artifact

Revision ID: db5ca83fadfc
Revises: 2dfb9215a144
Create Date: 2025-09-30 09:01:12.332144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5ca83fadfc'
down_revision: Union[str, None] = '2dfb9215a144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('submission_artifact_group_version_idx', 'submission_artifact', ['submission_group_id', 'version_identifier'], unique=False)
    op.create_unique_constraint('uq_submission_artifact_group_version', 'submission_artifact', ['submission_group_id', 'version_identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_submission_artifact_group_version', 'submission_artifact', type_='unique')
    op.drop_index('submission_artifact_group_version_idx', table_name='submission_artifact')
    # ### end Alembic commands ###
