# Example Computor Deployment Configuration with Execution Backends
# This shows the two-level structure for execution backends:
# 1. Root level: Define the backends themselves
# 2. Course level: Reference which backends to link to each course

# Root level: Define execution backends that will be created/ensured in the system
execution_backends:
  # Default Temporal backend for all courses
  - slug: temporal.default
    type: temporal
    properties:
      task_queue: computor-tasks
      namespace: default
      timeout_minutes: 30
      max_retries: 3
  
  # High-performance Temporal backend for advanced courses
  - slug: temporal.high-performance
    type: temporal
    properties:
      task_queue: high-performance-tasks
      namespace: production
      timeout_minutes: 60
      max_retries: 5
      resources:
        cpu: 4
        memory: 8192
  
  # Legacy Prefect backend (for compatibility)
  - slug: prefect.legacy
    type: prefect
    properties:
      deployment: test-deployment
      url: http://prefect-server:4200/api

# Organizations with their course families and courses
organizations:
  - name: Computer Science Department
    path: cs
    description: Main CS department
    gitlab:
      url: https://gitlab.example.com
      token: ${GITLAB_TOKEN}
    
    course_families:
      - name: Introduction Courses
        path: intro
        description: Introductory programming courses
        
        courses:
          - name: Programming 101
            path: prog101
            description: Introduction to Programming
            
            # Course level: Reference backends by slug
            execution_backends:
              # Link to the default temporal backend
              - slug: temporal.default
              
              # Also link to legacy backend for compatibility
              - slug: prefect.legacy
                properties:
                  # Course-specific override (optional)
                  custom_timeout: 20
            
            content_types:
              - slug: assignment
                title: Assignment
                kind: assignment
                color: green
              - slug: unit
                title: Learning Unit
                kind: unit
                color: blue
          
          - name: Advanced Programming
            path: prog201
            description: Advanced programming concepts
            
            # This course uses the high-performance backend
            execution_backends:
              - slug: temporal.high-performance
                properties:
                  # Course-specific configuration
                  priority: high
                  dedicated_workers: 2
            
            content_types:
              - slug: assignment
                title: Assignment
                kind: assignment
                color: green

# Users can be defined here (optional)
users: []

# Global settings
settings:
  auto_create_gitlab_groups: true
  default_visibility: private