identifier: itpcp.pgph.py.lambda
version: '1.0'
title: Lambda Funktionen
description: Description of the Assignment
authors:
  - name: <given_name> <family_name>
    email: <email>
    affiliation: <institute>
maintainers:
  - name: <given_name> <family_name>
    email: <email>
    affiliation: <institute>
courseMaterials:
  - name: python
    url: https://www.python.org/
supportingMaterials:
  - name: python
    url: https://www.python.org/
license: MIT
content:
  types: []
  disciplines: []
  topics: []
  tools:
    - python
  tags:
    - python
properties:
  studentSubmissionFiles:
    - lambda.py
  additionalFiles: []
  testFiles: []
  studentTemplates: []
  executionBackend:
    slug: itpcp.exec.py
    settings: {}
    version: <eb_py_version>
