"""add_message_audit_log_table

Revision ID: 2bcd79895e02
Revises: c0bf9ff5fa4f
Create Date: 2025-10-20 00:51:22.696255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bcd79895e02'
down_revision: Union[str, None] = 'c0bf9ff5fa4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_audit_log',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_id', postgresql.UUID(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'RESTORED', name='messageauditaction'), nullable=False),
    sa.Column('old_title', sa.String(length=255), nullable=True),
    sa.Column('old_content', sa.String(length=16384), nullable=True),
    sa.Column('new_title', sa.String(length=255), nullable=True),
    sa.Column('new_content', sa.String(length=16384), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('msg_audit_action_idx', 'message_audit_log', ['action', 'created_at'], unique=False)
    op.create_index('msg_audit_message_idx', 'message_audit_log', ['message_id', 'created_at'], unique=False)
    op.create_index('msg_audit_user_idx', 'message_audit_log', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('msg_audit_user_idx', table_name='message_audit_log')
    op.drop_index('msg_audit_message_idx', table_name='message_audit_log')
    op.drop_index('msg_audit_action_idx', table_name='message_audit_log')
    op.drop_table('message_audit_log')
    # ### end Alembic commands ###
