"""add service_type_id FK to service and make service_type nullable

Revision ID: bc188591d940
Revises: ae31bd24638e
Create Date: 2025-10-29 11:52:02.560091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc188591d940'
down_revision: Union[str, None] = 'ae31bd24638e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('service_type_id', postgresql.UUID(), nullable=True))
    op.alter_column('service', 'service_type',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.create_index(op.f('ix_service_service_type_id'), 'service', ['service_type_id'], unique=False)
    op.create_foreign_key(None, 'service', 'service_type', ['service_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    # Data migration: Map old service_type strings to new service_type_id UUIDs
    # This maps the old string values to the Ltree paths in service_type table
    op.execute("""
        -- Update temporal_worker services
        UPDATE service
        SET service_type_id = (
            SELECT id FROM service_type WHERE path = 'worker.temporal'
        )
        WHERE service_type = 'temporal_worker';

        -- Log the migration
        DO $$
        BEGIN
            RAISE NOTICE 'Migrated % service records to use service_type_id',
                (SELECT COUNT(*) FROM service WHERE service_type_id IS NOT NULL);
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_index(op.f('ix_service_service_type_id'), table_name='service')
    op.alter_column('service', 'service_type',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.drop_column('service', 'service_type_id')
    # ### end Alembic commands ###
