"""standardize_datetime_timezone_support

Revision ID: c0bf9ff5fa4f
Revises: b8c9d0e1f2g3
Create Date: 2025-10-19 11:55:51.043491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0bf9ff5fa4f'
down_revision: Union[str, None] = 'b8c9d0e1f2g3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4096),
               existing_nullable=True)
    op.alter_column('session', 'device_label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('session', 'version',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'version',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('session', 'device_label',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('session', 'user_agent',
               existing_type=sa.String(length=4096),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
