"""Unit tests for the access-log credential redaction filter."""

import logging

import pytest

from computor_backend.utils.log_redaction import RedactQueryCredentialsFilter, redact_url

CODE = "lr_code_3f8a1c6e0d92"
STATE = "lr_state_a0b7e4d15c68"
ACCESS = "lr_access_9d2e6b0f41c7"
REFRESH = "lr_refresh_57c1a8e3d06b"


def _access_record(path):
    # Same shape uvicorn.access emits: (client, method, path+query, http_ver, status).
    return logging.LogRecord(
        "uvicorn.access", logging.INFO, __file__, 1,
        '%s - "%s %s HTTP/%s" %d', ("10.0.0.1:1234", "GET", path, "1.1", 302), None,
    )


@pytest.mark.parametrize(
    "path",
    [
        f"/auth/keycloak/callback?code={CODE}&state={STATE}",
        f"/auth/success?user_id=u&token={ACCESS}&refresh_token={REFRESH}",
        f"/coder/uabc/ws/?TOKEN={ACCESS}&Refresh_Token={REFRESH}#x",
        # A workspace URL nested (URL-encoded) in /auth/coder-reauth?next=...
        f"/auth/coder-reauth?next=%2Fcoder%2Fuabc%2Fws%2F%3Ftoken%3D{ACCESS}%26refresh_token%3D{REFRESH}",
    ],
)
def test_access_log_line_has_no_credentials(path):
    record = _access_record(path)
    assert RedactQueryCredentialsFilter().filter(record) is True
    line = record.getMessage()
    for secret in (CODE, STATE, ACCESS, REFRESH):
        assert secret not in line
    assert "[REDACTED]" in line
    assert path.split("?", 1)[0] in line  # the route stays readable


def test_non_credential_params_are_kept():
    assert redact_url("/api/items?page=2&codename=x&mytoken=y") == "/api/items?page=2&codename=x&mytoken=y"


@pytest.mark.parametrize(
    "path",
    [
        # Percent-encoded parameter names: the server decodes them to code/state.
        f"/auth/keycloak/callback?%63ode={CODE}&%73tate={STATE}",
        f"/auth/keycloak/callback?C%6FDE={CODE}&St%61te={STATE}",
        # Doubly encoded nested query, as generated by coder-reauth -> login.
        "/auth/keycloak/login?redirect_uri=https%3A%2F%2Fcomputor.at%2Fapi%2Fauth%2Fcoder-reauth"
        f"%3Fnext%3D%252Fcoder%252Fu1%252Fws%253Ftoken%253D{ACCESS}%2526refresh_token%253D{REFRESH}",
        # Encoding nested deeper than the redactor looks through: redacted as uncertain.
        f"/x?next=%2525252525253Ftoken%2525252525253D{ACCESS}",
        f"/ws?token={ACCESS}",
    ],
)
def test_encoded_names_and_nested_queries_are_redacted(path):
    line = redact_url(path)
    for secret in (CODE, STATE, ACCESS, REFRESH):
        assert secret not in line


# --- transport: the real logging configs, a real uvicorn server --------------------

import asyncio  # noqa: E402
import io  # noqa: E402
import json  # noqa: E402
import runpy  # noqa: E402
import socket  # noqa: E402
from pathlib import Path  # noqa: E402
from types import SimpleNamespace  # noqa: E402
from unittest.mock import AsyncMock, Mock, patch  # noqa: E402
from urllib.parse import urlencode, urlsplit  # noqa: E402

SERVER_PY = Path(__file__).resolve().parents[2] / "server.py"
USER = "0232de59-e05d-4bc2-898f-b879c06abcde"


@pytest.fixture
def restore_logging():
    """server.py reconfigures global logging; put everything back afterwards."""
    manager = logging.Logger.manager
    loggers = [logging.getLogger()] + [
        lg for lg in manager.loggerDict.values() if isinstance(lg, logging.Logger)
    ]
    saved = {lg: (lg.level, list(lg.handlers), list(lg.filters), lg.propagate, lg.disabled)
             for lg in loggers}
    yield
    for lg in [logging.getLogger()] + [
        x for x in manager.loggerDict.values() if isinstance(x, logging.Logger)
    ]:
        level, handlers, filters, propagate, disabled = saved.get(lg, (logging.NOTSET, [], [], True, False))
        lg.setLevel(level)
        lg.handlers[:] = handlers
        lg.filters[:] = filters
        lg.propagate = propagate
        lg.disabled = disabled


def _load_server_logging(mode):
    """Run the checked-in entry point up to uvicorn.run; return (log_config, buffer)."""
    import uvicorn

    with patch.object(uvicorn, "run") as launch:
        runpy.run_path(str(SERVER_PY), run_name="__main__")
    buffer = io.StringIO()
    if mode == "uvicorn_log_config":
        config = launch.call_args.kwargs["log_config"]
        for handler in config["handlers"].values():
            handler["stream"] = buffer
        return config, buffer
    # setup_logging(): the root StreamHandler shared by uvicorn.access/.error.
    for handler in logging.getLogger().handlers:
        handler.setStream(buffer)
    return None, buffer


class _Redis:
    def __init__(self):
        self.data = {}

    async def set(self, key, value, **kwargs):
        self.data[key] = value

    async def get(self, key):
        return self.data.get(key)

    async def getdel(self, key):
        return self.data.pop(key, None)

    async def delete(self, key):
        return self.data.pop(key, None)


async def _exercise_transport(log_config, buffer):
    import httpx
    import uvicorn
    import websockets
    from fastapi import FastAPI

    from computor_backend.api import auth
    from computor_backend.permissions.principal import Principal
    from computor_backend.websocket import router as ws
    from computor_backend.websocket.auth import WebSocketAuthError, WebSocketCredential

    app = FastAPI()
    app.include_router(auth.auth_router)
    app.include_router(ws.ws_router)
    app.dependency_overrides[auth.get_db] = lambda: Mock()
    app.dependency_overrides[auth._coder_request_principal] = lambda: None
    registry = Mock()
    registry.get_enabled_plugins.return_value = ["keycloak"]
    registry.ensure_plugin_ready = AsyncMock(return_value=object())
    registry.get_login_url.side_effect = lambda p, cb, state: f"https://idp.invalid/a?state={state}"
    redis = _Redis()
    exchange = AsyncMock(return_value={"user_id": USER, "account_id": "a1", "is_new_user": False,
                                       "token": ACCESS, "refresh_token": REFRESH})
    manager = Mock(send_to_connection=AsyncMock(), disconnect=AsyncMock())

    async def connect(websocket, principal):
        await websocket.accept()
        return SimpleNamespace(websocket=websocket, principal=principal, credential=None)

    manager.connect = connect
    accepted = (Principal(user_id=USER), WebSocketCredential(kind="api_token", expires_at=None))
    ws_auth = AsyncMock(return_value=accepted)

    sock = socket.socket()
    sock.bind(("127.0.0.1", 0))
    port = sock.getsockname()[1]
    server = uvicorn.Server(uvicorn.Config(app, log_config=log_config, lifespan="off"))
    with patch.object(auth, "get_plugin_registry", return_value=registry), \
         patch("computor_backend.redis_cache.get_redis_client", AsyncMock(return_value=redis)), \
         patch("computor_backend.business_logic.auth.handle_sso_callback", exchange), \
         patch.object(ws, "authenticate_websocket_token", ws_auth), \
         patch.object(ws, "manager", manager), \
         patch.object(ws, "_watch_credential_expiry", AsyncMock()), \
         patch.dict("os.environ", {"NEXT_PUBLIC_API_URL": "https://computor.at/api"}):
        task = asyncio.create_task(server.serve(sockets=[sock]))
        try:
            for _ in range(200):
                if server.started:
                    break
                await asyncio.sleep(0.01)
            assert server.started
            async with httpx.AsyncClient(base_url=f"http://127.0.0.1:{port}", trust_env=False) as client:
                for code_key, state_key in [("code", "state"), ("%63ode", "%73tate")]:
                    redis.data[f"sso_state:{STATE}"] = json.dumps(
                        {"provider": "keycloak", "redirect_uri": "/auth/success"})
                    resp = await client.get(f"/auth/keycloak/callback?{code_key}={CODE}&{state_key}={STATE}")
                    assert resp.status_code == 302
                    assert exchange.await_args.kwargs["code"] == CODE  # server decoded the names
                # Real coder-reauth -> login hop: the workspace query ends up doubly encoded.
                nxt = f"/coder/u1/workspace?token={ACCESS}&refresh_token={REFRESH}"
                reauth = await client.get("/auth/coder-reauth?" + urlencode({"next": nxt}))
                parts = urlsplit(reauth.headers["location"])
                login = await client.get(parts.path.removeprefix("/api") + "?" + parts.query)
                assert login.status_code == 302
            async with websockets.connect(f"ws://127.0.0.1:{port}/ws?token={ACCESS}"):
                pass
            ws_auth.side_effect = WebSocketAuthError(4001, "invalid token")
            try:  # rejected: closed with 4001 (or refused, depending on timing)
                async with websockets.connect(f"ws://127.0.0.1:{port}/ws?token={REFRESH}") as conn:
                    await conn.recv()
            except Exception:
                pass
            assert ws_auth.await_count == 2
        finally:
            server.should_exit = True
            await task
    return buffer.getvalue()


@pytest.mark.asyncio
@pytest.mark.parametrize("mode", ["uvicorn_log_config", "setup_logging"])
async def test_transport_logs_carry_no_credentials(mode, restore_logging):
    log_config, buffer = _load_server_logging(mode)
    logs = await _exercise_transport(log_config, buffer)
    # The oracle only means something if the lines were actually logged.
    assert "/auth/keycloak/callback?" in logs
    assert "/auth/keycloak/login?" in logs
    assert logs.count('"WebSocket /ws?') >= 2  # accepted and rejected handshakes
    for secret in (CODE, STATE, ACCESS, REFRESH):
        assert secret not in logs
