function startWatching(directory)
%STARTWATCHING Set up the watcher state and start its timer.

stopWatching();

if ~isfolder(directory)
    [created, message] = mkdir(directory);
    if ~created
        error('figurewatch:directory', ...
            'Cannot create figure folder ''%s'': %s', directory, message);
    end
end

% BusyMode 'drop' matters: exporting a heavy figure can outlast the period,
% and queued-up ticks would then republish the same figure over and over.
watchTimer = timer( ...
    'Name', 'ComputorFigureWatch', ...
    'ExecutionMode', 'fixedSpacing', ...
    'Period', 0.5, ...
    'BusyMode', 'drop', ...
    'TimerFcn', @(~, ~) poll(), ...
    'ErrorFcn', @(~, event) warning('figurewatch:tick', ...
        'Figure watching hit an error: %s', event.Data.message));

watchState(struct( ...
    'Directory', directory, ...
    'Tracked', emptyTracked(), ...
    'Timer', watchTimer));
dirtyFigures(gobjects(1, 0));

start(watchTimer);
end


function tracked = emptyTracked()
%EMPTYTRACKED The 0x0 struct array that one tracked figure is a row of.
tracked = struct( ...
    'Figure', {}, ...
    'Number', {}, ...
    'Axes', {}, ...
    'Listeners', {}, ...
    'Name', {}, ...
    'Published', {});
end
