from typing import Protocol, runtime_checkable
from .schemas import CreateGitUserRequest, GitUser, GitServerHealthResponse, UpdateGitUserRequest


@runtime_checkable
class GitServerClient(Protocol):
    async def health(self) -> GitServerHealthResponse: ...
    async def create_user(self, req: CreateGitUserRequest) -> GitUser: ...
    async def get_user(self, username: str) -> GitUser: ...
    async def update_user(self, username: str, req: UpdateGitUserRequest) -> GitUser: ...
    async def delete_user(self, username: str) -> None: ...
    async def suspend_user(self, username: str) -> None: ...
    async def activate_user(self, username: str) -> None: ...
