import logging
from types import SimpleNamespace
from typing import Annotated
from uuid import UUID

import httpx
from fastapi import Depends, Query, Request, Response
from sqlalchemy.orm import Session
from computor_backend.permissions.auth import get_current_principal
from computor_backend.permissions.core import can_perform_action, check_course_permissions
from computor_backend.permissions.principal import Principal

from computor_backend.database import get_db
from computor_backend.api.api_builder import CrudRouter, invalidate_request_principal
from computor_backend.exceptions import (
    ConflictException,
    ForbiddenException,
    NotFoundException,
    RateLimitException,
    ServiceUnavailableException,
)
from computor_backend.interfaces import CourseInterface
from computor_backend.model import Course, CourseMember
from computor_backend.redis_cache import get_redis_client
from computor_backend.services.storage_service import get_storage_service
from computor_backend.business_logic.cascade_deletion import (
    count_course_entities,
    course_delete_block_reason,
    delete_course_cascade,
)
from computor_backend.business_logic.course_git import (
    execute_course_git_teardown,
    plan_course_git_teardown,
    resolve_template_archive_source,
)
from computor_backend.business_logic.course_ownership import invalidate_user_membership_caches
from computor_backend.websocket import publish_course_updated
from computor_backend.business_logic.course_template_export import (
    build_hierarchical_mapping,
    remap_archive_to_hierarchy,
)
from computor_backend.business_logic.course_registration import (
    list_public_courses as list_public_courses_bl,
)
from computor_backend.api._pagination import paginated_list
from computor_types.cascade_deletion import CascadeDeleteResult
from computor_types.courses import CoursePublicList, CoursePublicQuery

logger = logging.getLogger(__name__)

course_router = CrudRouter(CourseInterface)


async def _publish_course_archived(course, permissions) -> None:
    """Archiving hides the whole course from its students — tell their clients."""
    try:
        publish_course_updated(str(course.id), "archived")
    except Exception:  # noqa: BLE001 - a broadcast must never fail the write
        logger.exception("Failed to publish archive event for course %s", getattr(course, "id", None))


async def _publish_course_unarchived(course, permissions) -> None:
    try:
        publish_course_updated(str(course.id), "unarchived")
    except Exception:  # noqa: BLE001
        logger.exception("Failed to publish unarchive event for course %s", getattr(course, "id", None))


# ``PATCH /courses/{id}/archive`` and ``/unarchive`` are generated by the
# CrudRouter from ``Course.archived_at``; only owners pass (handlers_course).
course_router.on_archived.append(_publish_course_archived)
course_router.on_unarchived.append(_publish_course_unarchived)

# Each download pulls the whole template archive from the git server and, in
# hierarchical mode, rebuilds the zip in memory — cheap enough to click a few
# times in a row, not something to hammer.
TEMPLATE_DOWNLOAD_LIMIT = 10
TEMPLATE_DOWNLOAD_WINDOW = 60


async def check_template_download_rate_limit(user_id: str, cache) -> bool:
    """True once the user has spent their template-download budget.

    Fixed window per user, Redis-backed so it holds across workers. Fails open:
    this protects the git server from accidental hammering, it is not a
    security control.
    """
    key = f"rate_limit:template_download:{user_id}"
    try:
        count = await cache.incr(key)
        if count == 1:
            await cache.expire(key, TEMPLATE_DOWNLOAD_WINDOW)
        return count > TEMPLATE_DOWNLOAD_LIMIT
    except Exception as e:
        logger.error(f"Template download rate limit check failed: {e}")
        return False


@course_router.router.get(
    "/public",
    response_model=list[CoursePublicList],
    summary="Browse courses open for self-registration",
)
async def list_public_courses(
    response: Response,
    permissions: Annotated[Principal, Depends(get_current_principal)],
    params: Annotated[CoursePublicQuery, Depends()],
    db: Session = Depends(get_db),
):
    """Courses a lecturer has opened for student self-registration.

    Authenticated but role-free: every signed-in user sees the same catalog,
    including users who hold no role anywhere. That is the point — this is how
    someone with no memberships finds their first course.

    Metadata only. Course contents, members, git configuration and organization
    internals stay behind the normal permission checks; registering is a
    separate call. Declared before the generated ``GET /{id}`` route: module
    level decorators run at import time, so this static path is matched first
    (see CrudRouter.register_routes).
    """
    items, total = list_public_courses_bl(params, permissions, db)
    return paginated_list(items, total, response=response)


@course_router.router.get(
    "/{course_id}/template",
    responses={200: {"content": {"application/zip": {}}}},
    summary="Download the course template as a ZIP",
)
async def download_course_template(
    course_id: UUID,
    permissions: Annotated[Principal, Depends(get_current_principal)],
    db: Session = Depends(get_db),
    cache=Depends(get_redis_client),
    hierarchical: bool = Query(
        default=False,
        description=(
            "false: the student-template repo as it is in git (example "
            "directories). true: directories follow the course-content tree — "
            "unit/assignment titles name the directories; files not belonging "
            "to a deployed assignment are omitted."
        ),
    ),
):
    """Download the current course template, flat or re-arranged hierarchically.

    Rate limit: 10 downloads per minute per user (429 once exhausted).
    """
    if permissions.is_admin or "_organization_manager" in permissions.roles:
        # Global managers reach every course without a membership row.
        course = db.query(Course).filter(Course.id == str(course_id)).first()
    else:
        course = (
            check_course_permissions(permissions, Course, "_lecturer", db)
            .filter(Course.id == str(course_id))
            .first()
        )
    if course is None:
        raise ForbiddenException(
            detail="Downloading the course template requires the lecturer role"
        )

    user_id = permissions.get_user_id()
    if await check_template_download_rate_limit(str(user_id), cache):
        raise RateLimitException(
            error_code="RATE_001",
            detail="Too many template downloads. Please wait before trying again.",
            retry_after=TEMPLATE_DOWNLOAD_WINDOW,
            context={
                "limit": TEMPLATE_DOWNLOAD_LIMIT,
                "window_seconds": TEMPLATE_DOWNLOAD_WINDOW,
            },
        )

    url, headers, filename = resolve_template_archive_source(str(course_id), db)
    async with httpx.AsyncClient(timeout=60.0, follow_redirects=True) as client:
        upstream = await client.get(url, headers=headers)
    if upstream.status_code != 200:
        raise ServiceUnavailableException(
            detail="Could not fetch the template archive from the git server.",
            context={"upstream_status": upstream.status_code},
        )

    content = upstream.content
    if hierarchical:
        mapping = build_hierarchical_mapping(str(course_id), db)
        content = remap_archive_to_hierarchy(content, mapping)
        stem = filename[:-4] if filename.endswith(".zip") else filename
        filename = f"{stem}-hierarchical.zip"

    return Response(
        content=content,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@course_router.router.delete(
    "/{course_id}",
    response_model=CascadeDeleteResult,
    summary="Delete course and all course-specific data",
    description="""
    Delete a course and ALL its data including:
    - All course members (NOT the users themselves)
    - All course groups
    - All course content types and contents
    - All submission groups and their artifacts
    - All results and grades
    - All messages targeted to the course
    - The course's template and reference repositories on the git server

    Student repositories on the git server are KEPT (see
    `student_repositories_kept` in the result).

    Only a course `_owner` or an administrator may call this. A course that
    holds submissions from students is refused (409) for owners; an
    administrator may delete it once it has been archived.

    **WARNING**: This is a destructive operation. Use dry_run=true to preview;
    a preview reports `blocked_reason` when the real call would be refused.
    """
)
async def delete_course_endpoint(
    course_id: UUID,
    request: Request,
    permissions: Annotated[Principal, Depends(get_current_principal)],
    db: Session = Depends(get_db),
    dry_run: bool = Query(
        default=False,
        description="If true, only returns preview without deleting"
    ),
) -> CascadeDeleteResult:
    """Delete course and all course-specific data."""
    cid = str(course_id)
    # Through the course permission handler (``delete`` -> course ``_owner``).
    # Checked before existence so a non-member learns nothing, and on dry runs
    # too: the preview is not for people who could not delete.
    if not can_perform_action(permissions, Course, "delete", resource_id=cid):
        raise ForbiddenException(
            detail="Only an owner of this course (or an administrator) can delete it."
        )

    course = db.query(Course).filter(Course.id == cid).first()
    if not course:
        raise NotFoundException(detail=f"Course not found: {course_id}")

    counts = count_course_entities(db, cid)
    blocked_reason = course_delete_block_reason(
        counts,
        archived=course.archived_at is not None,
        is_admin=bool(permissions.is_admin),
    )
    if blocked_reason and not dry_run:
        raise ConflictException(detail=blocked_reason)

    # Everything the post-commit steps need is read NOW: the binding row goes
    # with the course, and every loaded instance expires on the cascade's
    # commit.
    plan = plan_course_git_teardown(cid, db)
    member_user_ids = [
        str(uid) for (uid,) in
        db.query(CourseMember.user_id).filter(CourseMember.course_id == cid).distinct().all()
    ]

    storage = get_storage_service()
    result = await delete_course_cascade(
        db=db,
        course_id=cid,
        storage=storage,
        dry_run=dry_run,
        counts=counts,
    )
    result.student_repositories_kept = plan.student_repositories_kept
    if dry_run:
        result.git_repositories = plan.repo_labels
        result.blocked_reason = blocked_reason
        return result

    if result.errors:
        # The database cascade did not commit; leave the git server alone.
        return result

    # Database first, git second — the same order the cascade uses for MinIO.
    # An orphaned template repo is recoverable by hand; a deleted template on a
    # course that still exists is not.
    deleted, git_errors = execute_course_git_teardown(plan, db)
    result.git_repositories = deleted
    result.errors.extend(git_errors)

    # Every member just lost a membership: their course-membership and view
    # caches would otherwise keep answering for a course that is gone. The
    # course's own view tags and the caller's cached Principal likewise.
    for uid in member_user_ids:
        invalidate_user_membership_caches(uid)
    course_router._invalidate_caches_for(SimpleNamespace(id=cid))
    try:
        publish_course_updated(cid, "deleted")
    except Exception:  # noqa: BLE001
        logger.exception("Failed to publish delete event for course %s", cid)
    await invalidate_request_principal(request, what="deleting a course")

    return result
